version: "3.9"

services:
  api:
    build:
      context: .
    container_name: booking-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    restart: unless-stopped